# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 6, 47, 57, 999695)),
        ),
    ]
